### ISSUE TITLE
TOC技术委员会委员资格定义

### ISSUE THREAD

**Issue by xiaods** [Conflux-DAO-TOC/toc#1]
1、有技术开发背景，对区块链技术很了解
2、给Conflux技术社区做过最少一个项目贡献
3、愿意承担委员会一个主题项目的leader工作，推动这个主题项目的维护管理工作
4、保证有1年的时间来持续参与委员会的治理工作，开会，协调，报告
5、愿意接受技术社区的监督，如果遇到质疑需要给出合理解释并通过评审考核

**Comment by haifengcui0529** [comment]
期待conflux在行业内大放异彩，有幸参与其中很是感激，一起学习，加油！

**Comment by xiaods** [comment]
加油 @haifengcui0529

**Comment by xiaods** [comment]
update to toc project.
