### ISSUE TITLE
委员申请：chy

### ISSUE THREAD

**Issue by chy2021** [Conflux-DAO-TOC/toc#10]
Introduce：
Two years E-commerce platform development and operations experiences. (example: http://baihuo.fr);
Three years traditional information system project experiences: management and development;
and 0.5 years think about Blockchain system.

github: https://github.com/chy2021

关注的Conflux项目：
https://github.com/Conflux-Chain/conflux-rust
https://github.com/Conflux-Chain/java-conflux-sdk
CRC
Dapp
本人愿意承担一年期的技术 委员会的治理工作。

**Comment by xiaods** [comment]
done
