### ISSUE TITLE
委员申请：Funny

### ISSUE THREAD

**Issue by Lsw931102** [Conflux-DAO-TOC/toc#11]
介绍：
Four years of front-end development work, with certain project experience in online tourism, distribution industry and education industry, during which I also led some development teams.

github:
https://github.com/Lsw931102

参与的conflux项目：
https://github.com/Conflux-Dev/conflux-wallet
https://github.com/Conflux-Dev/conflux-benefit
https://github.com/Conflux-Tech-Community/NFT-Front-End
https://github.com/Conflux-Tech-Community/Flux-Front-End
https://github.com/angelia-yuqi-personal/conflux-website

本人愿意承担一年期技术委员会的治理工作

**Comment by xiaods** [comment]
done
