### ISSUE TITLE
委员申请：dandan (郄建军)

### ISSUE THREAD

**Issue by dandantadie** [Conflux-DAO-TOC/toc#13]
2000年---2018在北京广播电台、中央人民广告电台、中国国际广播电台，从事媒体运营和广告经营工作。2015年从事移动媒体、自媒体工作、今日头条、微信朋友圈、腾讯智慧推、百度搜索等媒体服务工作和移动互联网项目孵化工作。
技术背景介绍：
1熟悉掌握区块链底层技术原理和认知，多种共识机制，智能合约定义。
2认知数字货币TOKEN解决传统金融双花痛点问题。
3掌握应用层区块链+物联网、区块链+知识产权、区块链+大数据、区块链+金融、区块链+社区平台等多种技术解决方案原理。
个人拥有资源：
拥有资源：移动媒体合作资源、全国400多家广播电台节目资源、北京电台FM1039、FM974、国际台FM88.7、中央台中国之声FM106.6、FM96.6等主流媒体节目合作资源。

2018年初创建“链客社区”目前是国内唯一的垂直区块链开发者社区，注册用户10w+，日活5000+，成为了国内外区块链技术爱好者专业的学习交流平台。链客社区问答为用户实际解决10000多次开发者问题，拥有15000+原创笔记、多系类完整视频课堂体系2000课时、社区《节点池》板块深度参与国际知名公链的节点治理，并给开发者投资者提供节点投资平台服务。社区吸引N多区块链技术领域知名KOL，聚集众多区块链技术爱好者。
《链客TALK》为区块链技术发声！目前TALK自媒体与国内外知名项目AMA直播活动38期，活动总曝光次数过亿，文章阅读300多万人次。

Conflux社区贡献：
目前链客社区是Conflux的媒体大使之一，曾数次利用链客社区自身资源及影响
力，视频制作Conflux链客TALK、AMA活动、采访等形式为Conflux引流并参与
社区共识，目前链客团队全程参与Conflux主网测试所有阶段。

治理认知态度：
在治理过程中的“无为与有为”以社区生态健康发展为初心，做敢于发声、努力建设生态的有为人，面对工作中私名私利要时刻谨记初心做无为人。

建立治理体系：
重点在于生态治理体系建立与完善，人才精英培养！公开透明平等治理体系保证行动中相互协作保证质量提高效率过程，打造认知共识，最终目标是为社区生态健康蓬勃发展。 

生态治理孵化：
以生态需求工具类项目为基础，完善自身生态体系，为Conflux上的DAPP方提供相应的支持，并围绕重点领域提供多样板的区块链商业解决方案吸引项目方参与Conflux生态建设。打造Conflux区块链商业落地标杆。

**Comment by xiaods** [comment]
done
