### ISSUE TITLE
委员申请：junhua(周军华)

### ISSUE THREAD

**Issue by ghost** [Conflux-DAO-TOC/toc#14]
周军华    节点共识CTO
北航计算机硕士

近10年的一线研发管理经验，先后任职中国软件、暴风在线等企业，连续创业者。

2017年开始接触区块链技术，并后续参与钱包、DEX、DAPP及区块链浏览器产品研发管理。

我们已与十几家公链建立了合作，参与他们社区基础服务建设，并贡献代码，在公链的生态落地上具备丰富的经验。

我们的资源优势：
1、DappBirds产品，我们的愿景是打造全球最好用的Dapp平台，并提供NFT资产的创造、应用场景展示、流通闭环生态合作。
2、在DeFi业务，我们也提供DEFI项目排行榜以及DEFI Token数据。
3、媒体宣发：蜂鸟财经（主打国内市场）、CoinBirds(海外市场)
4、市场营销：冲顶答题、红包裂变等工具

Conflux社区贡献：
DAppBirds是全球第一家支持Conflux公链的去中心化钱包，为用户体验钱包功能、体验DAPP功能提供了支持。并积极参与社区建设，提供了iOS SDK的版本开源给社区。接下里为Conflux用户带来的更好流动性的SWAP服务，未来会继续在Conflux生态上深耕。

Conflux治理理念：
1、主办技术大会，汇聚核心开发者，重要的技术路线里程碑或许通过辩论达到共识；
2、完善开发者工具，举办开发者大赛、黑客马拉松等，对技术布道，有更多的应用落地，公链的生态才能繁荣；
3、跨链技术就是实现价值网络的关键，优先发展跨链技术，实现价值的互联互通，价值共享；
4、开发者社区的提案计划，建立更多的资产标准；
5、公链底层安全机制建设完善，与可升级方案完备，避免硬分叉；

**Comment by xiaods** [comment]
+1
