### ISSUE TITLE
委员申请：Heisenberg

### ISSUE THREAD

**Issue by bingowrt** [Conflux-DAO-TOC/toc#16]
Heisenberg  现就职于 新浪微博
本硕均毕业于 中国石油大学（华东）
2020年 6月 加入Conflux 社区
2020年 11月-至今 担任 Conflux技术社区 生态项目测试验收组负责人，先后组织社区生态测试验收组成员对10于个生态项目进行测试验收，并整理验收报告。

正在参与的conflux社区项目：tspace 4.0.0 
https://github.com/Conflux-Tech-Community/Tspacev4.0-Front-End

力微任重，希望在技术委员会为conflux生态做出更多贡献

**Comment by xiaods** [comment]
安排。
