### ISSUE TITLE
Case: Conflux社区SIG-Conflux-Rust兴趣小组挖坑贴

### ISSUE THREAD

**Issue by xiaods** [Conflux-DAO-TOC/toc#3]
SIG-Conflux-Rust  这个兴趣小组主要是来参与conflux-rust项目的开发工作。争取成为commiter。谁有兴趣领导一下. conflux-rust是Conflux的核心主链项目，能成为它的commiter，将是荣誉所在。目前我们委员会需要在社区招募一名rust开发者来领导这个兴趣小组，欢迎报名参与

**Comment by xiaods** [comment]
+1  报名参与

**Comment by xiaods** [comment]
conflxu-rust这块，我已经公示，我会来领导社区Rust小组的组建和贡献，目前目标是进入conflux-rust项目的committer序列

**Comment by guanzizai288** [comment]
大家好，观自在前来学习，请多多指教。

之前跟着网络课程自学在以太坊发币；在《得到》学习梁宁的《产品思维》课程；希望能跟各位多多学习，并提供力所能及的帮助。

谢谢~~

**Comment by youlaiwuqu** [comment]
大家好，有来无去前来学习，请多多指教
之前大学学过一点C语言。

**Comment by ice0077** [comment]
+1 大家好，天天喝小米来学习，请多多指教！

**Comment by dyhbrewer** [comment]
+1
加入学习，业余也在学习Rust，用需求驱动学习效率更高

**Comment by haifengcui0529** [comment]
+1
坚持长期学习，更好的了解新技术和区块链，我来了

**Comment by xiaods** [comment]
https://github.com/Conflux-DAO-TOC/sig-conflux-rust  新组repo建立。

**Comment by xiaods** [comment]
close
