### ISSUE TITLE
委员申请：Frank Jin

### ISSUE THREAD

**Issue by cfx-gspos** [Conflux-DAO-TOC/toc#4]
Frank Jin
介绍： Mainly develop wbsite for HK enterpirse and  university system  over ten years.

github: https://github.com/chinajinwanjun

关注的Conflux项目：
https://github.com/Conflux-Chain/conflux-doc
https://github.com/Conflux-Chain/js-conflux-sdk

 
本人愿意承担一年期的技术 委员会的治理工作。

**Comment by xiaods** [comment]
+1

**Comment by xiaods** [comment]
@chinajinwanjun Frank，已经邀请你加入github组织，请approved.

**Comment by xiaods** [comment]
close
