### ISSUE TITLE
委员申请：三豐@HZ

### ISSUE THREAD

**Issue by aoems** [Conflux-DAO-TOC/toc#5]
三豐@HZ
介绍：
I Have been engaged in technology R & D and management in the top enterprises in the communication industry for more than 15 years.  During that time, I led the architecture design, development and maintenance of the network data back-end system.
  
github: https://github.com/aoems

关注的Conflux项目：
https://github.com/Conflux-Chain/js-conflux-sdk
https://github.com/Conflux-Chain/conflux-developer-site
https://github.com/Conflux-Chain/conflux-wallet
https://github.com/Conflux-Chain/conflux-portal-website

https://github.com/calmlism/Conflux-wallet

本人愿意承担一年期的技术 委员会的治理工作。

**Comment by xiaods** [comment]
+1

**Comment by xiaods** [comment]
@aoems  你有2个Github账号，我到底给你用哪个

三豐@hz  or  @aoems

我已经邀请你。你可以approved加入github组织。

**Comment by xiaods** [comment]
close
