### ISSUE TITLE
委员申请：Elliot Ning

### ISSUE THREAD

**Issue by elliot2008** [Conflux-DAO-TOC/toc#6]
Elliot Ning
介绍: 
Two years of blockchain development experience in NodePacific, and have some experience in eosio and libra's projects about plugin, block browser.

github:  https://github.com/elliot2008

关注的Conflux项目：
https://github.com/Conflux-Chain/conflux-rust
https://github.com/Conflux-Chain/go-conflux-sdk-for-wallet
https://github.com/Conflux-Chain/go-conflux-sdk

本人愿意承担一年期的技术 委员会的治理工作。

**Comment by xiaods** [comment]
欢迎加入

**Comment by ice0077** [comment]
谢谢！收到！

**Comment by xiaods** [comment]
close
