### ISSUE TITLE
委员申请：youyou

### ISSUE THREAD

**Issue by kevin1027sloth** [Conflux-DAO-TOC/toc#8]
introduce：I have been engaged in the Internet e-commerce industry for more than two years, and have worked as PM project for many times during this period, led the team to fight many battles, and had certain project experience in the development of DAPP

github: https://github.com/xiaozhu001
参与Conflux项目：

https://github.com/Conflux-Chain/conflux-nft-contract
本人愿意承担一年期的 技术委员会 的治理工作。

**Comment by xiaods** [comment]
+1
