### ISSUE TITLE
委员申请：Lm

### ISSUE THREAD

**Issue by calmlim** [Conflux-DAO-TOC/toc#9]
Introduction: For ten years, I have been engaged in many industries such as GIS, Internet, and blockchain, and have some experience in research and development, products, and management. He has participated in other blockchain projects, and participated in the research and development of simple underlying, browser, wallet, DAPP and other types of projects. Willing to progress and grow with the Conflux project.

github:https://github.com/calmlism

参与Conflux项目:
1、https://github.com/Conflux-Chain/conflux-nft-contract
2、https://github.com/calmlism/Conflux-wallet
3、https://github.com/calmlism/conflux-crc721
4、https://github.com/calmlism/java-conflux-sdk

本人愿意承担一年期的技术 委员会的治理工作。

**Comment by xiaods** [comment]
done
